services:
  postgres:
    image: postgres:16-alpine
    container_name: reservas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reservas}
      POSTGRES_USER: ${POSTGRES_USER:-reservas_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-reservas_pass_dev}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-reservas_user} -d ${POSTGRES_DB:-reservas}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reservas-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: reservas-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@reservas.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - reservas-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reservas-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      SPRING_DATASOURCE_USERNAME: postgres.akzpawuhiqavbubdvoeb
      SPRING_DATASOURCE_PASSWORD: ${SUPABASE_DB_PASSWORD:-nZwJy3JRLbIeLPcx}
      SPRING_FLYWAY_URL: jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_FLYWAY_USER: postgres.akzpawuhiqavbubdvoeb
      SPRING_FLYWAY_PASSWORD: ${SUPABASE_DB_PASSWORD:-nZwJy3JRLbIeLPcx}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    networks:
      - reservas-net

  # descomentar cuando se inicialice React
  frontend:
     build:
       context: ./frontend
       dockerfile: Dockerfile
     container_name: reservas-frontend
     restart: unless-stopped
     ports:
       - "${FRONTEND_PORT:-3000}:80"
     depends_on:
       - backend
     networks:
       - reservas-net

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  reservas-net:
    driver: bridge
